id: A890F7FE3
title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
type: translation
pechas:
- I43241751
- I886CC962
- IB8CCC31A
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:28.310530
  last_modified_at: 2023-01-04 12:07:28.310535
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I43241751/42E6: '4999'
  I886CC962/C464: '4999'
  IB8CCC31A/4BE0: '4999'
